# Generated by Django 2.2 on 2019-04-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pub_date',
            field=models.DateField(blank=True, null=True, verbose_name='Publication date'),
        ),
    ]
